service: sho
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: go1.x
  region: us-east-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  redirect:
    handler: bin/redirect
    environment: ${file(env.json)}
    events:
      - http:
          path: /{id}
          method: get
  create:
    handler: bin/create
    environment: ${file(env.json)}
    events:
      - http:
          path: /
          method: post